Add system metadata tags to files
keboola/output-mapping pull request #76
Opened 2021-02-11 12:28 UTC by pivnicek

2021-02-12 16:28 UTC, odinuv requested changes

2021-02-12 16:28 UTC, odinuv commented on src/Writer/FileWriter.php
> +use Keboola\OutputMapping\Exception\OutputOperationException;
is it used?

2021-02-12 16:28 UTC, odinuv commented on src/Writer/Helper/TagsRewriter.php
> +                $storageConfig['tags'][] = $systemKey . ': ' . $systemValue;
please name and enumerate them explicitly, this is gonna be huge chaos if half of the metadata is defined here https://github.com/keboola/output-mapping/blob/a53d90913686d8b0916855e3cef7e7ba430698de/src/Writer/TableWriter.php#L34 and the other half would be defined in docker-bundle
also component id is required https://github.com/keboola/output-mapping/blob/a53d90913686d8b0916855e3cef7e7ba430698de/src/Writer/TableWriter.php#L68 and the others are optional https://github.com/keboola/output-mapping/blob/a53d90913686d8b0916855e3cef7e7ba430698de/src/Writer/TableWriter.php#L557

2021-02-12 16:28 UTC, odinuv commented on src/Writer/FileWriter.php
> +                $storageConfig = TagsRewriter::addSystemTags($storageConfig, $systemMetadata);
it doesn't really rewrite tags, does it?

2021-02-12 16:28 UTC, odinuv commented on tests/Writer/AbsWriterWorkspaceTest.php
> +        $this->assertEquals($expectedTags, $file1["tags"]);
single quotes pls

2021-02-12 16:28 UTC, odinuv commented on tests/Writer/AbsWriterWorkspaceTest.php
> +            'rowId: 12345',
in reality, this has to be `configurationRowId` https://github.com/keboola/ex-google-bigquery-v2/blob/524a0f220cbf3fa1c1d6275859c1dbb86ced8899/src/OutputMappingStrategy/Files.php#L56 
which ofc makes no difference here, but `rowId: 12345` simply should not be produced

2021-02-12 16:31 UTC, pivnicek commented on src/Writer/FileWriter.php
> +                $storageConfig = TagsRewriter::addSystemTags($storageConfig, $systemMetadata);
no, but it manipulates tags, so I guess I can either change the class name or make a new class

2021-02-12 16:33 UTC, pivnicek commented on src/Writer/Helper/TagsRewriter.php
> +                $storageConfig['tags'][] = $systemKey . ': ' . $systemValue;
lol 
![image](https://user-images.githubusercontent.com/569139/107794931-59701780-6d58-11eb-8e9a-a725c14cb762.png)

2021-02-12 17:14 UTC, odinuv commented on src/Writer/Helper/TagsRewriter.php
> +        if (!empty($systemMetadata)) {
condition not needed (also always true in reality)

2021-02-12 17:15 UTC, odinuv commented on src/Writer/Helper/TagsRewriter.php
> +                switch ($systemKey) {
ok, so if you did it this way then, you can actually check it via in_array($systemkey, [FileWriter::SYSTEM_KEY_COMPONENT_ID, ...] and else log something like "key XY ignored"

2021-02-12 17:18 UTC, pivnicek commented
right on, thanks man, I'll update accordingly

2021-02-16 20:30 UTC, odinuv commented on tests/Writer/StorageApiWriterTest.php
> +    const DEFAULT_SYSTEM_METADATA = ['componentId' => 'foo'];
not used

2021-02-16 20:31 UTC, odinuv commented
seems ok (when the tests pass)

2021-02-17 11:55 UTC, odinuv commented on tests/Writer/StorageApiWriterTest.php
> +            'configurationRowId' => '7998-configurationRowId: 12345',
a bit strange value for configuration row id

2021-02-17 11:56 UTC, pivnicek commented on tests/Writer/StorageApiWriterTest.php
> +            'configurationRowId' => '7998-configurationRowId: 12345',
yeah, that's not right at all :-) thanks

2021-02-17 11:58 UTC, odinuv commented on tests/Writer/StorageApiWriterTest.php
> +            'configurationRowId' => '7998-configurationRowId: 12345',
it's an opaque string, so in a way it doesn't matter. Looks weird though :)

2021-02-17 14:16 UTC, odinuv approved these changes

2021-02-17 15:13 UTC, merged